//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensurance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPolicy
    {
        public int ClientId { get; set; }
        public int PolicyId { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Policy Policy { get; set; }
    }
}
