//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensurance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CoverageType { get; set; }
        public System.DateTime StartDate { get; set; }
        public int CoverageTime { get; set; }
        public double Cost { get; set; }
        public int RiskType { get; set; }
        public decimal CoveragePercentage { get; set; }
    
        public virtual Coverage Coverage { get; set; }
        public virtual Risk Risk { get; set; }
    }
}
